export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REDUCE_PRODUCT_TO_CART = 'REDUCE_PRODUCT_TO_CART';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';

export const AUTH_STATUS = 'AUTH_STATUS';
export const GET_AUTH = 'GET_AUTH';
export const LOG_OUT = 'LOG_OUT';
export const AUth_REDIRECT_PATH = 'AUth_REDIRECT_PATH';